name: carbondiary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  google_place: ^0.4.7 # Lightweight autocomplete search
  # google_maps_flutter: ^2.6.1. # Interactive map, more set up

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logs.json
    - assets/images/
    - .env