name: carbondiary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  google_place: ^0.4.7 # Lightweight autocomplete search
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  dotted_line: ^3.2.3
  fl_chart: ^0.65.0
  url_launcher: ^6.3.2
  table_calendar: ^3.2.0
  # google_maps_flutter: ^2.6.1. # Interactive map, more set up

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/waste_data.json
    - assets/travel_data.json
    - assets/images/
    - assets/images/symbols/
    - assets/images/examples/
    - .env